/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo.java;

public class Item {

    protected Double price;

    public Item(Double price) {
        this.price = price;
    }

    public Double getPrice() {
        return this.price;
    }
}
