/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package demo.java;

import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.assertEquals;

class ItemRelatedTests {
    @Test
    void iPutAPriceAndItWorks() {
        Item item = new Item(10.0);
        assertEquals(10.0, item.getPrice());
    }

    @Test
    void iUseDiscountAndItWorks() {
        ItemWithDiscount item = new ItemWithDiscount(10.0);
        item.calculateDiscount(20.0);
        assertEquals(8, item.getPrice(), "when using discount, the price is different");
    }

    @Test
    void butItBreaksLiskovSubstitutionPrinciple() {
        ItemWithDiscount item = new ItemWithDiscount(10.0);
        item.calculateDiscount(20.0);
        assertEquals(item.getPrice(), 8);

        Item originalItem = item;
        assertEquals( 10.0, originalItem.getPrice(), "This test would fail because the other class changes Item.getPrice behaviour by accident");



    }
}
